project: FacialLandmarkDetection
workspace_path: '/home/itamar/thesis/outputs'
log_interval: 20
pretrained:
  use_pretrained: False
  task_id: 72f1c231963b47f4bcb4e3a149c3c4e5
save_model: True
single_batch_debug: False

dataset:
  dataset_dir: '/home/itamar/thesis/DATASET'
  workset_name: 'WS03'

train:
  datasets:
    to_use: [ 'helen/trainset', 'afw' , 'lfpw/trainset'] # 'WFLW/trainset']
#    to_use: ['helen/trainset', 'lfpw/trainset', 'AFW' ]
    use_augmentations: True
    augmentations:
      scale: 0.25
      rotation_factor: 30
      flip_lr: True
  partition_seed: 42
  num_landmarks: 68
  input_size: [256, 256]
  trainset_partition: 0.8
  epochs: 250
  batch_size: 32
  torch_seed: 42
  trainable_parameters: null
  cuda:
    use: True
    device: 'cuda:0'
    device_type: 'cuda'
    num_workers: 4
    pin_memory: True
  backend:
    use_torch: True
  model: DETR
  optimizer: ADAMW
  scheduler: StepLR
  heatmaps:
    train_with_heatmaps: False
    hm_amp_factor: 100
    guassian_std: 1.5
    heatmap_size: [64, 64]
  rearrange_prediction_for_min_cos_max_bipartite: False

evaluation:
#  datasets: [ 'helen/testset']
  datasets: ['helen/testset', 'lfpw/testset', 'WFLW/testset', '300W', 'ibug', 'COFW68/COFW_test_color']
  exp_name: 'itsayag'
  prediction_from_decoder_head: -1