experiment:
  name: itsayag
  workspace_path: '/home/itamar/thesis/outputs'
  log_interval: 20
  pretrained:
    use_pretrained: False
    timestamp: '210121_161519'
  save_model: True
  single_batch_debug: False

dataset:
  dataset_dir: '/home/itamar/thesis/DATASET'
  workset_name: 'WS02'
  to_use: ['300W', 'AFW', 'COFW68', 'helen/trainset', 'helen/testset',
           'ibug', 'lfpw/trainset', 'lfpw/testset', 'menpo/trainset', 'WFLW/trainset', 'WFLW/testset']

train:
  datasets:
    to_use: ['lfpw/trainset', 'lfpw/testset', 'menpo/trainset', 'WFLW/trainset' ]
    use_augmentations: True
    augmentations:
      scale: 0.25
      rotation_factor: 30
      flip_lr: True
  partition_seed: 42
  num_landmarks: 68
  trainset_partition: 0.8
  epochs: 200
  torch_seed: 0
  batch_size: 20
  step_size: 5
  trainable_parameters: null
  hm_amp_factor: 100
  run_valid: True
  cuda:
    use: False
    device: 'cuda:1'
    device_type: 'cuda'
    num_workers: 1
    pin_memory: True
  backend:
    use_torch: True
  model: 'HRNET'
#  model: 'LMDT01'
  optimizer: 'ADAM'
  scheduler: 'StepLR'
  criteria: 'MSELoss'

optimizer:
  ADAM:
    lr: 0.0005
    betas: [0.5, 0.999]
    eps: 1e-8
    weight_decay: 0
    amsgrad: False
  SGD:
    lr: 0.1
    momentum: 0
    dampening: 0
    weight_decay: 0
    nesterov: False
  RANGER:
    lr: 0.001
    alpha: 0.5
    K: 6
    N_sma_threshhold: 5
    betas: [0.95, 0.999]
    eps: 1e-5
    weight_decay: 0
    use_gc: True
    gc_conv_only: False

model:
  LMDT01:
    output_branch: 'DPTS'
    input_size: [ 256, 256 ]
  HRNET:
    sigma: 1.5    # TODO: understand this parameter
    input_size: [256, 256]
    heatmap_size: [64, 64]
    target_type: 'Gaussian'

scheduler:
  StepLR:
    step_size: 200
    gamma: 0.3
  CyclicLR:
    base_lr: 1e-3
    max_lr: 1e-1
    step_size_up: 100

loss:
  MSELoss: null

evaluation:
  datasets: ['helen/testset', 'lfpw/testset', 'WFLW/testset', '300W', 'ibug', 'COFW68/COFW_test_color']
  exp_name: 'itsayag'
  timestamp: '210121_145942'