project: FacialLandmarkDetection
workspace_path: '/home/itamar/thesis/outputs'
log_interval: 20
pretrained:
  use_pretrained: False
  task_id: ed6f81cfc9f94533941b8e1801e5e4de
save_model: True
single_batch_debug: False

dataset:
  dataset_dir: '/home/itamar/thesis/DATASET'
  workset_name: 'WS02'
  to_use: [ '300W', 'AFW', 'COFW68', 'helen/trainset', 'helen/testset',
            'ibug', 'lfpw/trainset', 'lfpw/testset', 'menpo/trainset', 'WFLW/trainset', 'WFLW/testset' ]

train:
  datasets:
    to_use: [ 'helen/trainset', 'lfpw/trainset', 'menpo/trainset', 'AFW' ]
    #    to_use: ['helen/trainset', 'lfpw/trainset', 'AFW' ]
    use_augmentations: True
    augmentations:
      scale: 0.25
      rotation_factor: 30
      flip_lr: True
  partition_seed: 42
  num_landmarks: 68
  input_size: [ 256, 256 ]
  trainset_partition: 0.8
  epochs: 250
  batch_size: 4
  torch_seed: 42
  trainable_parameters: null
  run_valid: True
  cuda:
    use: True
    device: 'cuda:0'
    device_type: 'cuda'
    num_workers: 4
    pin_memory: True
  backend:
    benchmark: True
    use_torch: True
    cudnn_enabled: True
    cudnn_deterministic: False
    cudnn_benchmark: True
  model: TRXREFINE01
  optimizer: ADAM
  scheduler: MultiStepLR
  heatmaps:
    train_with_heatmaps: True
    hm_amp_factor: 100
    guassian_std: 2
    heatmap_size: [ 64, 64 ]
  rearrange_prediction_for_min_cos_max_bipartite: False

evaluation:
  #  datasets: [ 'helen/testset']
  datasets: [ 'helen/testset', 'lfpw/testset', 'WFLW/testset', '300W', 'ibug', 'COFW68/COFW_test_color' ]
  exp_name: 'itsayag'
  prediction_from_decoder_head: -1
  usa_tta: True
