dataset:
  to_use: ['300W', 'AFW', 'COFW68', 'helen/trainset', 'helen/testset',
           'ibug', 'lfpw/trainset', 'lfpw/testset', 'menpo/trainset', 'WFLW/trainset', 'WFLW/testset']
train:
  use_cuda: yes
  use_multi_loss_function: no
  log_interval: 10  # epochs
  datasets: ['lfpw/trainset', 'lfpw/testset', 'menpo/trainset', 'WFLW/trainset']
evaluation:
  datasets: []