experiment:
  name: detr
  workspace_path: '/home/itamar/thesis/outputs'
#  workspace_path: '/media/itamar/Itsayag_500Gb/500GB/Thesis/outputs'
  log_interval: 20
  single_image_train: False
  pretrained:
    use_pretrained: False
    timestamp: '220521_021837'
  save_model: True
  single_batch_debug: False

dataset:
  dataset_dir: '/home/itamar/thesis/DATASET'
  workset_name: 'WS02'
  to_use: ['300W', 'AFW', 'COFW68', 'helen/trainset', 'helen/testset',
           'ibug', 'lfpw/trainset', 'lfpw/testset', 'menpo/trainset', 'WFLW/trainset', 'WFLW/testset']

train:
  datasets:
    to_use: [ 'WFLW/trainset', 'helen/trainset', 'lfpw/trainset', 'menpo/trainset', 'AFW' ]
    use_augmentations: True
    augmentations:
      scale: 0.25
      rotation_factor: 30
      flip_lr: True
  partition_seed: 42
  num_landmarks: 68
  trainset_partition: 0.8
  epochs: 250
  batch_size: 64
  torch_seed: 42
  trainable_parameters: null
  hm_amp_factor: 100
  run_valid: True
  cuda:
    use: True
    device: 'cuda:0'
    device_type: 'cuda'
    num_workers: 4
    pin_memory: True
  backend:
    use_torch: True
  model: 'DETR'  # 'DETR', 'HRNET'
  optimizer: 'ADAMW'
  scheduler: 'StepLR'
  criteria: 'MSELoss'

optimizer:
  ADAM:
    lr: 0.0001
    betas: [0.5, 0.999]
    eps: 1e-8
    weight_decay: 0
    amsgrad: False
  SGD:
    lr: 0.1
    momentum: 0
    dampening: 0
    weight_decay: 0
    nesterov: False
  RANGER:
    lr: 1e-05
    alpha: 0.5
    K: 6
    N_sma_threshhold: 5
    betas: [0.95, 0.999]
    eps: 1e-05
    weight_decay: 0
    use_gc: True
    gc_conv_only: False
  ADAMW:
    lr: 1e-4
    weight_decay: 0.0001

model:
  LMDT01:
    output_branch: 'DPTS'
    input_size: [ 256, 256 ]
  HRNET:
    sigma: 1.5
    input_size: [ 256, 256 ]
    heatmap_size: [ 64, 64 ]
    target_type: 'Gaussian'
    config: 'models/HRNET/face_alignment_300w_hrnet_w18.yaml'
  DETR:
    input_size: [ 256, 256 ]
    heatmap_size: [ 64, 64 ]
    backbone: 'resnet50'

scheduler:
  MultiStepLR:
    milestones: [50, 150]
    gamma: 0
  StepLR:
    step_size: 50
    gamma: 0.5
  CyclicLR:
    base_lr: 1e-3
    max_lr: 1e-1
    step_size_up: 100

loss:
  MSELoss: null

evaluation:
#  datasets: [ 'helen/testset']
  datasets: ['helen/testset', 'lfpw/testset', 'WFLW/testset', '300W', 'ibug', 'COFW68/COFW_test_color']
  exp_name: 'itsayag'
  prediction_from_decoder_head: -1
